### ISSUE TITLE
Add support for 1.9.51.0

### ISSUE THREAD

**Issue by ArisuSanchez** [gazzamc/starfield_hex_updater#10]
Updated 2 days ago, patiently waiting for an update to this thanks

**Comment by ArisuSanchez** [comment]
actually give me a momeent im reading thru your instructions and see if i can patch it myself

**Comment by ArisuSanchez** [comment]
update could  not patch it myself, tried manually grabbing sfse and  putting it in the sfse folder from its repo, then tried to patch  it,  the  patch  failed 

![image](https://github.com/gazzamc/starfield_hex_updater/assets/82681339/6b13f087-b121-49f3-a5a5-35c734d9bf34)

unsure of  what to do next as i am computer literate but only  enough to do  basic things

**Comment by gazzamc** [comment]
@Chibi-Usa I had put it on hold until the big update mentioned by Bethesda, as most mods reverted back to using offsets rather than the address lib, so the amount of work required to update both this and patch various mods (I used myself) wasn't worth the effort in the short term.

I'll have a look later today

**Comment by gazzamc** [comment]
@Chibi-Usa I've added the hex file for `v1.9.51` and updated the patcher, I haven't extensively tested mods but I can confirm at least 1 or 2 address library mods work. Let me know how you fare

**Comment by ArisuSanchez** [comment]
xbox  or something screwed  me over, i am  unable to do *anything* to the starfield exe

**Comment by ArisuSanchez** [comment]
okay i figured out how to move the starfield exe, just delete  it,  and then you can move it from the  recycle bin to other directorys

**Comment by ArisuSanchez** [comment]
Okay did my testing and my version didnt work at all,  but your hex file does so yay, thanks again for making this tool

**Comment by ArisuSanchez** [comment]
@gazzamc could you add the 
> okay i figured out how to move the starfield exe, just delete it, and then you can move it from the recycle bin to other directorys


to your instructions  under the starfield exe section?

**Comment by gazzamc** [comment]
> @gazzamc could you add the
> 
> > okay i figured out how to move the starfield exe, just delete it, and then you can move it from the recycle bin to other directorys
> 
> to your instructions under the starfield exe section?

Cutting/Pasting works also and is in the [docs](https://github.com/gazzamc/starfield_hex_updater/tree/main/docs#cant-move-exe), but the powershell script already has this option under "Copy/Hardlink game files"

**Comment by ArisuSanchez** [comment]
it wont work when the xbox app edits the exes permissions via SYSTEM
