### ISSUE TITLE
Still receiving "MS Gamepass Version" error when running sfse_loader after patching

### ISSUE THREAD

**Issue by theFisher86** [gazzamc/starfield_hex_updater#13]
I left this in a Reddit comment awhile ago as well. 

After downloading a fresh SFSE install, patching, building and hardlinking I still receive the "You have the MS Store/Gamepass version of Starfield, which is not compatible with SFSE." error when launching sfse_loader.exe.

It's worth noting that when running the powershell script I receive an error about being unable to copy Starfield.exe and the need to manually copy it but I don't think that's the issue because it _does_ copy Starfield.exe into the copy folder. And sfse_loader.exe doesn't throw the "I can't find starfield.exe" error. Nonetheless the original install path for me is G:/Games/Starfield/Content/starfield.exe and my copy folder is G:\Games\

StarfieldCopy\starfield.exe. Starfield.exe is successfully copied to the G:\Games\StarfieldCopy folder after running the script.

I've attached my log files for reference:
 [logfile_2024.05.23_09.04.15.log](https://github.com/gazzamc/starfield_hex_updater/files/15417351/logfile_2024.05.23_09.04.15.log)

And here's a screenshot of my StarfieldCopy folder
![Screenshot 2024-05-23 211549](https://github.com/gazzamc/starfield_hex_updater/assets/8523246/51d64775-d4a1-4092-9cfb-9d1abf1896c8)

**Comment by gazzamc** [comment]
Hello,

I believe I responded to your message, but reddit isn't exactly great for debugging/troubleshooting. 

As I said in my previous message, the log looks good apart from the copying issue, so just a couple of things we can check.

`Did you run the powershell script as admin?`
`In the tools folder (repo root), do you see PSTools?`
`What version of Powershell are you running?` (type "$PSVersionTable" into powershell to check).

Just from looking at the screen of your files, it seems the exe may still have the permissions intact, which could be the cause of the issue, it is odd that you're getting that specific message as I patch that out specifically.

Lets try fix the executable permissions first, can you do the following.

- Delete `Starfield.exe` from `G:\Games\StarfieldCopy` and from `G:/Games/Starfield/Content/`
- Open the Xbox app, go to `Starfield -> Manage -> Files -> Verify and Repair`.
<details>

![repair xbox](https://github.com/gazzamc/starfield_hex_updater/assets/7975925/e3580ea8-b908-465c-980b-afda962a83ab)

</details>

- Open the game via the Xbox app after the repair process, you can exit once you get to main menu.
- Here you've two options, if you have the `PSTools` mentioned above you can either retry to copy the executable via the powershell script or the manual way to remove the permissions.
- - Open the powershell script (via the bat file of choice, ensuring to accept the admin privs), choose `Option 5 > Option 2`, if it fails again move to the next step.
- - To manually copy it we need to go to the game folder `G:/Games/Starfield/Content/` and DELETE `starfield.exe`, once deleted you can press CTRL + Z ( or open the recycling bin and restore the file), if it successfully removed the permissions it should look like the image below.
- - - Once the executable is showing the icon, you can copy/paste it like any other file, just manually copy it into `G:\Games\StarfieldCopy`
- Try booting via `Starfield.exe` in `G:\Games\StarfieldCopy` first, it should boot.
- Try booting via SFSE
- Profit??

<details>
<summary>Starfield exectuable with permissions removed</summary>

![image](https://github.com/gazzamc/starfield_hex_updater/assets/7975925/8432426c-5e62-4c4d-bdb9-8de2e4f016c2)

</details>

If none of the above works, can you attach the SFSE logs, you can find them in `C:\Users\{username}\Documents\My Games\Starfield\SFSE\Logs`, maybe it will give me more information.

**Comment by gazzamc** [comment]
Sorry I didn't notice when writing the first reply, but you have the new game folder in the same root as your Xbox install, this folder is controlled by the Xbox app and would explain why you cant remove the permissions.

Can you copy the game files and sfse to `G:\Starfield` (or any folder outside of `Games` on this drive) and retrying.

**Comment by theFisher86** [comment]
Okay, can confirm the permissions were the problem. A few notes regarding what I was able to do to get it working:

- The powershell script just couldn't do the copying trick to fix the permissions for whatever reason.
- It being in my G:/Games/ folder wasn't the problem (I created and own that folder not Xbox)
- Deleting Starfield.exe and hitting ctrl-z _or_ "Restoring" from the Recycle Bin didn't work. The restored file still didn't have an icon and was locked. 
- However, if I cut the file from Recycle Bin and placed it into StarfieldCopy (or presumably anywhere) it didn't "relock" the permissions.
- So the process that I believe will work is Delete Starfield.exe from .../Starfield/Content/Starfield.exe --> Enter the Recycle Bin --> Cut Starfield.exe from the Recycle Bin and paste to .../StarfieldCopy/Starfield.exe

**Comment by gazzamc** [comment]
> * It being in my G:/Games/ folder wasn't the problem (I created and own that folder not Xbox)

Can you elaborate on this more, so that I can test locally? 

You created the folder and set it as the install location via the xbox app? or you created it and moved the original starfield folder to it?  

Your game install was `G:\Games\Starfield\Content`, so `Games` must have been set as the install folder, which means that xbox has taken control over it. 
If you could take a screenshot of the security tab of the folder, with the `User` group selected it would help, similar to the one I've added.

<details>
<summary>Permissions</summary>

![image](https://github.com/gazzamc/starfield_hex_updater/assets/7975925/a0f5392c-f9cb-4584-9b5f-23d5c40bd6a9)

</details>

Thanks

**Comment by gazzamc** [comment]
Update:

I was able to reproduce your issue, it is due to the permissions and mainly due to the folder being inside the xbox install folder, even if you did create it, it will inherit the permissions from it's parent folder and will have the same restrictions as the original game folder.

- During my test, I was able to copy the exe to the new game folder but it failed when trying to copy it back to the original folder (permissions we're not removed).
- When switching the new game folder to a folder located outside of the xbox install folder I was successfully able to copy the exe (and remove the permissions).

I will update the script with a check for the folder location, and better error handling for the exception you received when trying to copy the exe.

I appreciate the feedback, as frustrating as it might be.

**Comment by theFisher86** [comment]
> If you could take a screenshot of the security tab of the folder, with the `User` group selected it would help, similar to the one I've added.

Here is the permissions showing me owning the G:\Games folder (I blacked out my name but both of the blackedout sections are me):
![Screenshot 2024-05-24 100308](https://github.com/gazzamc/starfield_hex_updater/assets/8523246/46ed4f39-2306-475a-b8b4-e5931095ec99)

To note the differences the Starfield folder is owned by SYSTEM and the Content folder (within Starfield) is owned by Administrators (similar to how Starfield.exe appeared to owned by Administrators but had the weird encryption thing).

I think checking folder permissions is a good thing to do regardless but I can't find any unusual restrictions at all inside the G:\Games folder, it's not until I get into a game MS Game folder (ie Starfield) that the weird permissions start coming up. 

I guess my point is worst case scenario if someone else has a similar problem the delete to Recycle Bin and move it from there method seems pretty foolproof and will avoid any permissions issues that may exist. 

Thank you for all your help!

**Comment by gazzamc** [comment]
That's pretty interesting, it will pass the folder check in this case, but I've added the check on the exe itself after the move, so at the very least there's better context on the error. 

I haven't been able to programmably simulate the Recycle Bin method, but i've updated the docs and there's now this thread, so hopefully if someone is experiencing the same issues, they find it. I'll keep looking into it though.

The oddest part is, I'm moving the exe with SYSTEM privileges so it's weird that it can't be copied back, I'll try re-create your scenario with the folder and it might give me more insight.
