### ISSUE TITLE
Better Guide W/ Pictures

### ISSUE THREAD

**Issue by ArisuSanchez** [gazzamc/starfield_hex_updater#2]
Hi can you create a guide with pictures, i keep screwing up somewhere and i cannot figure out how to fix up my screwup via text, as im not that great at text instructions

thanks

**Comment by gazzamc** [comment]
Hi,

I don't think you did anything incorrect, after adding the images to the guide I noticed that one of the commands were outdated, I've now corrected this, so thanks for bringing this to my attention.

Let me know if it's more helpful with the images I've added.

**Comment by ArisuSanchez** [comment]
Okay thank you!  i will  check it out now

**Comment by ArisuSanchez** [comment]
![image](https://github.com/gazzamc/starfield_hex_updater/assets/82681339/d980ef89-b970-4343-a4cd-c14be062dee5)
okay so i did auto install and had this error when i checked, i should just manually install this yes?

**Comment by gazzamc** [comment]
Looks like it can't find `vswhere.exe`, Can you double check it's in the tools folder? if not you can download it from [here](https://github.com/Microsoft/vswhere/releases/), it should have downloaded it before checking.

If possible, could you link the log files or send it via email `gazzzamc+patcher[at]gmail.com` if you don't want to expose you specs, if it's not downloading I'll like to be sure the url is correct, or add an alternative.

**Comment by ArisuSanchez** [comment]
yeah i did auto install first then checked, looks like it didnt auto install
[logfile_script_2023.10.29_03.57.39.log](https://github.com/gazzamc/starfield_hex_updater/files/13199663/logfile_script_2023.10.29_03.57.39.log)
[logfile_build_2023.10.29_03.57.39.log](https://github.com/gazzamc/starfield_hex_updater/files/13199664/logfile_build_2023.10.29_03.57.39.log)
and here are the logs

**Comment by gazzamc** [comment]
It looks like it did build, but the logs are limited atm unfortunately so there's only so much I can see, I feel it might be the relative path in the command to check for the compiler.

I've added a fix for the path to vswhere, which should hopefully fix the error you're getting, if you have the chance to re-check with the latest update I'd appreciate it.

Thanks

Edit:

You seem to have all the dependencies (according to the log, I see the compiler in the build log), so if the new update doesn't work you can still complete the process from the menu itself. If you `copy/hardlink` the files first then go to the `SFSE` menu option, and select each option from `1...4`.

**Comment by Chibi-Usa** [comment]
i managed to get it to work up until i tried to use sfse

![image](https://github.com/gazzamc/starfield_hex_updater/assets/82681339/7d992942-5b6a-4cfc-8d71-41e9680d32da)

**Comment by Chibi-Usa** [comment]
actually that might be my bad
lemme  delete everything and try again

**Comment by ArisuSanchez** [comment]
okay nvm excuse my deleting posting i did something wrong 
could not find starfield.exe was the error i got
[logfile_script_2023.10.29_07.28.47.log](https://github.com/gazzamc/starfield_hex_updater/files/13200182/logfile_script_2023.10.29_07.28.47.log)
[logfile_build_2023.10.29_07.28.47.log](https://github.com/gazzamc/starfield_hex_updater/files/13200183/logfile_build_2023.10.29_07.28.47.log)

**Comment by ArisuSanchez** [comment]
ACTUALLY NVM, DIDNT SEE THE STARFIELD.EXE TRANSFER ERROR

read thru the docs and transfered starfield.exe by cutting from /xboxgames/ to the folder then _copying_ back to /xboxgames/


edit: in the docs add a snippit in the gui section for the movement of starfield.exe

**Comment by gazzamc** [comment]
`Starfield.exe` is moved during the Auto Install process. There's also an option under the `Copy/Hardlink Game Files` option.

![image](https://github.com/gazzamc/starfield_hex_updater/assets/7975925/c2d3c3d3-d854-47a3-aac5-329ad0b2f04c)

Could you post the error for the transfer? as that's not normal.

Edit:

I didn't see the error you posted above:

`could not find starfield.exe was the error i got`

Did you include the `content` folder in the `GamePath`? eg. `C:\XboxGames\Starfield\Content` 

Unfortunately these errors won't show up on the log.

**Comment by ArisuSanchez** [comment]
no the error popped up in a random cmd window that closed itself
regardless thats what happened to me starfield.exe didnt move at all and now that i manually moved it sfse works, 

so does plugins.txt enabler despite it appearing in the incompatable side of things?

**Comment by gazzamc** [comment]
I believe I fixed the issue, I'm now forcing the `content` folder if it's omitted when setting paths. Yes, `plugins.txt` works I just forgot to move it. I'll update it now.

Appreciate the help. I'll close this now as you seem to be set.
