### ISSUE TITLE
Request: Starfield Hard Link for Game Pass Mod

### ISSUE THREAD

**Issue by rtfmoz2** [gazzamc/starfield_hex_updater#6]
Create mod for the hardlink process.

**Comment by gazzamc** [comment]
Hardlinking option in included in the powershell script.

**Comment by rtfmoz2** [comment]
Yes I know. I was just reading why you cant include the SFSE files. Damn shame.

**Comment by rtfmoz2** [comment]
How do I find the right commit id?
