### ISSUE TITLE
Request: SFSE for Game Pass Mod

### ISSUE THREAD

**Issue by rtfmoz2** [gazzamc/starfield_hex_updater#7]
Is there way we can package this up as **SFSE for Game Pass** mod so we only have to install pre-compiled files. Then make the mod outlined in #6 a requirement for this mod?

**Comment by gazzamc** [comment]
I don't have the license to re-distribute the binary files, I've asked the mod author and he refused to give me the permission. Please remove the link to the file as this goes against the mod owners wishes.

Thanks
